# Base configs
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Photography by Tiffany & Sammy"
subtitle: "The University of Georgia 2020"
author: "Tiffany & Sammy"
header:
 title: "Photography"
 subtitle: "by Tiffany & Sammy"
footer:
 name: "Tiffany & Sammy"
 bio: "The Univeristy of Georgia, Fall 2020"
social_urls:
  github: "https://github.com/TiffyxSammy"
